apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  annotations:
    app.kubernetes.io/name: speedtest-exporter
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: speedtest-exporter
spec:
  selector:
    app: speedtest-exporter
  ports:
  - name: http
    port: 9798
