---
- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: base
  tasks:
    - include_role:
        name: k3s/download
      vars:
        k3s_version: v1.24.2+k3s1
    - name: Ensure open-iscsi is installed
      ansible.builtin.apt:
        name: open-iscsi
        state: present

- hosts: k3s_master
  become: true
  roles:
    - role: k3s/master
      vars:
        master_ip: "{{ hostvars[groups['k3s_master'][0]]['ansible_host'] | default(groups['k3s_master'][0]) }}"
        extra_server_args: "--node-label hunet.uk/ethernet-speed={{ ethernet_speed }} --node-label hunet.uk/disk={{ disk }} --disable servicelb --disable traefik --kube-apiserver-arg default-not-ready-toleration-seconds=30 --kube-apiserver-arg default-unreachable-toleration-seconds=30 --kube-controller-arg node-monitor-period=20s --kube-controller-arg node-monitor-grace-period=20s --kubelet-arg node-status-update-frequency=5s"
    - role: helm
    - role: argocd

- hosts: k3s_node
  become: true
  roles:
    - role: k3s/node
      vars:
        master_ip: "{{ hostvars[groups['k3s_master'][0]]['ansible_host'] | default(groups['k3s_master'][0]) }}"
        extra_agent_args: "--node-label hunet.uk/ethernet-speed={{ ethernet_speed }} --node-label hunet.uk/disk={{ disk }} --kubelet-arg node-status-update-frequency=5s"
