- name: updating hostname {{ inventory_hostname }} (2/2)
  become: true
  ansible.builtin.copy:
    content: "{{ inventory_hostname }}{{'\n'}}"
    dest: /etc/hostname
    mode: 0644
    backup: true
  register: hostname_change
  notify:
    - Reboot
    - Wait

- name: update hostsfile
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1{{'\t'}}{{ inventory_hostname }}" # noqa: no-tabs
    backup: true
    state: present
  notify:
    - Reboot
    - Wait

- name: 'Update APT package cache'
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe
