apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest-exporter
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    path: kubernetes/speedtest-exporter
    repoURL: https://github.com/ahume/home-infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
